### PR TITLE
Use buf-action in CI

### PR DESCRIPTION
**Pull request by emcfarlane**
This updates CI to use the new buf-action replacing buf-setup, buf-lint, buf-breaking and buf-push unifying these tasks as one. We implement the default behaviour described [here](https://github.com/bufbuild/buf-action?tab=readme-ov-file#default-behavior). Changes from the current behaviour include: added`format` as an additional check, moved checks to run on the pull_request event, sync changes on push and delete for all branches, push is no longer conditional on checks.

Tasks remaining:
- [ ] replace `lint` and `breaking` status checks for the buf checks job.

### CODE REVIEW

**Comment by nicksnyder** [comment]
> The behaviour tries to keep consistent with the old CI behaviour.


I don't think this should be our goal as we are migrating to the new action. I think when migrating toward the new action, we should assume by default we want to have the default behavior the GitHub action provides, unless there is a specific reason to deviate.

**Comment by emcfarlane** [comment]
@nicksnyder behaviour here is enforced by the environment: https://github.com/bufbuild/knit-proto/actions/runs/9391209655
Secrets are guarded to the production environment on the main branch. I've taken this as a requirement for this repository.

**Comment by nicksnyder** [comment]
@jhump can you share context on how/why we are using GitHub environments in this repo?

**Comment by jhump** [comment]
@nicksnyder, I'm afraid that I have no idea. Strangely, that line in `.github/workflows/buf.yaml` is from the very first commit in this repo, yet it does not exist in its predecessor (an internal-only repo that has since been archived: https://github.com/bufbuild/knit-api-archive). Maybe Infra did something here to constrain the push action or to make it work? I don't actually know how environments work or what exactly that was intended to do. And unfortunately, I am not able to find any threads in Slack where this was discussed. Sorry 🤷.

**Comment by nicksnyder** [comment]
Ok, thanks for the context @jhump.

@emcfarlane can you update this PR to be your original commit https://github.com/bufbuild/knit-proto/pull/8/commits/30c25e99a34e1afcff67c69fecd17a99c84a173b and then we can work on making whatever environment changes to make it green.

@rubensf @DMarby can you help fix the configuration on this repo so we can either push to "production" environment from branches or just not have/use environments at all? (If we need an environment, maybe we should be clear that the environment is actually called "BSR" or "buf.build")

**Comment by emcfarlane** [comment]
@nicksnyder switched to default behaviour.

**Review by nicksnyder — APPROVED** [review]
update PR description please

**Pull request merged**
